export const countryCodeList =[
    {
        name:"Afghanistan",
        code:"+93"
    },
    {
        name:"Argentina",
        code:"+54"
    },
    {
        name:"Australia",
        code:"+61"
    },
    {
        name:"Bahrain",
        code:"+973"
    },
    {
        name:"Bangladesh",
        code:"+61"
    },
    {
        name:"Bhutan",
        code:"+61"
    },
    {
        name:"Brazil",
        code:"+61"
    },
    {
        name:"Bulgaria",
        code:"+61"
    },
    {
        name:"Canada",
        code:"+61"
    },
]